# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# Increase timeout because `nodejs` can sometimes take longer.
command_timeout = 1000

# Removing modules from here disables them
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$docker_context\
$package\
$nodejs\
$python\
$rust\
$cmd_duration\
$jobs\
$battery\
$line_break\
$character"""

[username]
format = "[ $user]($style) @ "  # nf-fa-circle_user

[hostname]
ssh_symbol = " "  # nf-fa-laptop
style = "bold green"
format = "[$ssh_symbol$hostname]($style) · "

[directory]
read_only = " "  # nf-fa-lock

[git_branch]
symbol = " "  # nf-oct-git_branch
format = '\[[$symbol$branch]($style)\] '

[git_commit]
tag_symbol = " "  # nf-fa-tag
only_detached = false
format = '\[[ $hash]($style)\] '

[docker_context]
symbol = "  "  # nf-oct-container
format = '\[[$symbol$context]($style)\] '

[package]
symbol = " "  # nf-oct-package
format = '\[[$symbol$version]($style)\] '

[nodejs]
symbol = "󰎙 "  # nf-md-nodejs
format = '\[[$symbol($version)]($style)\] '

[python]
symbol = " "  # nf-seti-python
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\] '

[rust]
symbol = " "  # nf-seti-rust
format = '\[[$symbol($version)]($style)\] '

[cmd_duration]
format = '\[[󰔛 $duration]($style)\] '  # nf-md-timer_outline

[battery]
format = '\[[$symbol$percentage]($style)\] '

# Remapping symbols to updated Material Design Icons from Nerd Fonts.
full_symbol = "󰁹 "  # nf-md-battery
charging_symbol = "󰢟 "  # nf-md-battery_charging_outline
discharging_symbol = "󱃍 "  # nf-md-battery_alert_variant_outline
unknown_symbol = "󱉞 "  # nf-md-battery_off_outline
empty_symbol = "󰂎 "  # nf-md-battery_outline

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 20
style = "yellow"
