# CAUTION: Symlinked file!
# ORIGINAL: `dotfiles/helix/languages.toml`

# Reference: https://github.com/helix-editor/helix/blob/master/languages.toml

[[language]]
name = "json"
file-types = ["code-workspace"] # TODO: Remove when commit 0cdeee7/PR #14908 lands.
indent = { unit = "\t", tab-width = 2 }
