# This is the 1Password SSH agent config file, which customizes the
# behaviour of the SSH agent.
#
# Use it to:
# - Enable specific keys from specific vaults.
# - Control the order in which keys are offered to SSH servers.

[[ssh-keys]]
vault = "Personal"
item = "Ed25519"

[[ssh-keys]]
vault = "Automattic"
item = "Ed25519 (A8c)"

[[ssh-keys]]
vault = "FinRep"
item = "Ed25519 (FinRep)"
