#!/usr/bin/env bash

# This script will perform the follow steps:
#
# - Configures Zsh with a `.zshenv` file.
# - Install Oh My Zsh.
# - Configure Oh My Zsh by customising the `.zshrc` file.

# to use the XDG Base Directory specification
# via a `.zshenv` file. Then it installs Oh My Zsh and configures it by
# editing the autogenerated `.zshrc` file.

# Configure Zsh using a `.zshenv` file.
# If a `.zshenv` file already exists, back it up.
if [ -f "$HOME/.zshenv" ]; then
	echo "Backing up existing .zshenv file..."
	mv "$HOME/.zshenv" "$HOME/.zshenv.bak"
fi
ln -s "$HOME/dotfiles/zsh/.zshenv" "$HOME/.zshenv"
source "$HOME/.zshenv"

# Install Oh My Zsh.
if $(command -v omz >/dev/null); then
	echo "Oh My Zsh is already installed."
else
	echo "Installing Oh My Zsh..."
	curl -fsSL https://install.ohmyz.sh/ | bash -s -- --unattended
fi

# Disable Oh My Zsh themes because we use Starship.
# Enable auto-updates for Oh My Zsh.
# Activate specific plugins for my workflow.
# Set `ZSH_CUSTOM` to the `dotfiles/zsh/custom/` directory.
sed -i '' \
	-e 's|^ZSH_THEME=.*$|ZSH_THEME=""|' \
	-e "s|^# zstyle ':omz:update' mode auto|zstyle ':omz:update' mode auto|" \
	-e 's|^plugins=.*$|plugins=(brew git nvm terraform)|' \
	-e 's|^.*ZSH_CUSTOM=.*$|ZSH_CUSTOM="$HOME/dotfiles/zsh/custom"|' \
	"$ZDOTDIR/.zshrc"
